repos:
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: "v5.10.1" # Use the revision sha / tag you want to point at
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.7.1" # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic
          - httpx
