name: Publish Testing

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-n-publish:
    name: Upload release to PyPI Test
    runs-on: ubuntu-latest
    env:
      name: pypi
      url: https://test.pypi.org/p/chainlit-python-client
    permissions:
      contents: read
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python setup.py sdist
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          password: ${{ secrets.PYPI_API_TOKEN_TESTING }}
          repository-url: https://test.pypi.org/legacy/
